// Per-run storage. Each pipeline run gets its own folder under runs/, holding all its
// artifacts + a meta.json. A generated runs/INDEX.md is the human table-of-contents.
//
// Replaces the old overwritten runner/artifacts/ and the flat history/ folder.

import { mkdirSync, writeFileSync, readFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";

export const runsDir = (root) => join(root, "runs");
export const runDir = (root, runId) => join(runsDir(root), runId);

// First meaningful line of a request — used for labels and slugs.
export function firstLine(request) {
  return request.split("\n").find((l) => l.trim() && !l.startsWith("#"))?.trim() ?? request.trim();
}

export function slugify(s) {
  return String(s).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48) || "run";
}

// e.g. 2026-06-02-143005-add-a-csv-export-endpoint  (sorts chronologically by name)
export function makeRunId(label, date = new Date()) {
  const ts = date.toISOString().slice(0, 19).replace("T", "-").replaceAll(":", "");
  return `${ts}-${slugify(label)}`;
}

const STATUS_LABEL = {
  shipped: "✅ shipped",
  halted: "⛔ halted",
  escalated: "⚑ escalated",
  "rolled-back": "↩ rolled-back",
  error: "💥 error",
  running: "⏳ running",
  stopped: "■ stopped",
};
const label = (s) => STATUS_LABEL[s] || s || "?";
const cell = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");

// Read every run's meta.json, newest first (ids start with a timestamp).
export function listRuns(root) {
  const dir = runsDir(root);
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => {
      let meta = {};
      try { meta = JSON.parse(readFileSync(join(dir, d.name, "meta.json"), "utf8")); } catch { /* no/invalid meta */ }
      return { id: d.name, ...meta };
    })
    .sort((a, b) => (a.id < b.id ? 1 : -1));
}

// Regenerate runs/INDEX.md from all meta.json files.
export function writeIndex(root) {
  const runs = listRuns(root);
  const rows = runs.map((r) => {
    const when = (r.startedAt || "").slice(0, 16).replace("T", " ") || r.id;
    const ticket = r.linearUrl ? `[${r.ticket || "ticket"}](${r.linearUrl})` : (r.ticket || "—");
    return `| ${when} | ${label(r.status)} | ${cell(r.request)} | ${ticket} | [\`${r.id}\`](./${encodeURIComponent(r.id)}/) |`;
  });
  const md = [
    "# Runs",
    "",
    `_${runs.length} run${runs.length === 1 ? "" : "s"}, newest first. Generated by the pipeline — do not edit by hand._`,
    "",
    "| When (UTC) | Status | Request | Ticket | Folder |",
    "|---|---|---|---|---|",
    ...rows,
    "",
  ].join("\n");
  mkdirSync(runsDir(root), { recursive: true });
  writeFileSync(join(runsDir(root), "INDEX.md"), md);
}
